# pdf

In [1]:
#importando as bibliotecas
import numpy as np
import pandas as pd

In [2]:
# == CÓDIGO 1 == #
Z = np.zeros((4, ))
print("Z:", Z)

Z: [0. 0. 0. 0.]


In [3]:
# == CÓDIGO 2 == #
Z = np.zeros((4, ))
Z[1] = 1
print("Z:", Z)

Z: [0. 1. 0. 0.]


In [4]:
# == CÓDIGO 3 == #
Z = np.zeros((4, ))
Z[1:] = 1
print("Z:", Z)

Z: [0. 1. 1. 1.]


In [5]:
# == CÓDIGO 4 == #
Z = np.zeros((4, ))
Z[0:3] = 1
print("Z:", Z)

Z: [1. 1. 1. 0.]


In [26]:
# == CÓDIGO 5 == #
X = 2 * np.ones((2,2))
print("X:\n", X)

X:
 [[2. 2.]
 [2. 2.]]


In [7]:
# == CÓDIGO 6 == #
X = np.array([[1,2],[3,4]])
Y = X[0, :]
Y[1] = 10
print("X:\n", X)

X:
 [[ 1 10]
 [ 3  4]]


In [32]:
# == CÓDIGO 7 == #
X = np.array([[1,3],[11,10]])
print(np.mean(X[X > np.pi]))

10.5


In [16]:
# == CÓDIGO 8 == #
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 
                  'cat', 'snake', 'cat', 'dog', 'dog'],
       'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7,3],
       'visits': [1,3,2,3,2,3,1,1,2,1],
       'priority': ['yes', 'yes', 'no', 'yes', 'no',
                   'no', 'no', 'yes', 'no', 'no',]}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
data
#labels

{'animal': ['cat',
  'cat',
  'snake',
  'dog',
  'dog',
  'cat',
  'snake',
  'cat',
  'dog',
  'dog'],
 'age': [2.5, 3, 0.5, nan, 5, 2, 4.5, nan, 7, 3],
 'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
 'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

In [12]:
# == CÓDIGO 9 == #
df = pd.DataFrame(data=data, index=labels)
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [17]:
# == CÓDIGO 10 == #
y_true = np.array([1., 2., 1.])
y_pred = np.array([1.1, 1.98, 1.05])

# Teste

In [24]:
# == CÓDIGO 4 == #
Z = np.ones((4,)) 
Z[4] = 0.
print("Z:", Z)

IndexError: index 4 is out of bounds for axis 0 with size 4

In [25]:
# == CÓDIGO 4 == #
Z = np.zeros((4, )) 
Z[:3] = 1.
print("Z:", Z)

Z = np.ones((4,)) 
Z[-1] = 0
print("Z:", Z)

Z = np.zeros((4, )) 
Z[:-1] = 1.
print("Z:", Z)

Z: [1. 1. 1. 0.]
Z: [1. 1. 1. 0.]
Z: [1. 1. 1. 0.]


In [30]:
# == CÓDIGO 5 == #
X = 2 * np.ones((2,2))
print("X:\n", X)

X = np.ones((2, 2)) + np.ones((2, 2))
print("X:\n", X)

X = np.array([2.] * 4).reshape(2, 2)
print("X:\n", X)

X:
 [[2. 2.]
 [2. 2.]]
X:
 [[2. 2.]
 [2. 2.]]
X:
 [[2. 2.]
 [2. 2.]]


In [28]:
# == CÓDIGO 5 == #
X = np.twos((2, 2))
print("X:\n", X)

AttributeError: module 'numpy' has no attribute 'twos'

In [35]:
df.rows_cols

AttributeError: 'DataFrame' object has no attribute 'rows_cols'

In [39]:
df.len

AttributeError: 'DataFrame' object has no attribute 'len'

In [38]:
df.length

AttributeError: 'DataFrame' object has no attribute 'length'

In [40]:
df.shape

(10, 4)

In [44]:
df['animal'].value_counts()

cat      4
dog      4
snake    2
Name: animal, dtype: int64

In [45]:
type(df['animal'].value_counts())

pandas.core.series.Series

In [46]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [48]:
print(df['visits'])
print(type(df['visits']))

a    1
b    3
c    2
d    3
e    2
f    3
g    1
h    1
i    2
j    1
Name: visits, dtype: int64
<class 'pandas.core.series.Series'>


In [49]:
print(df.iloc[:, -2])
print(type(df.iloc[:, -2]))

a    1
b    3
c    2
d    3
e    2
f    3
g    1
h    1
i    2
j    1
Name: visits, dtype: int64
<class 'pandas.core.series.Series'>


In [50]:
print(df.iloc[:, 3])
print(type(df.iloc[:, 3]))

a    yes
b    yes
c     no
d    yes
e     no
f     no
g     no
h    yes
i     no
j     no
Name: priority, dtype: object
<class 'pandas.core.series.Series'>


In [51]:
print(df.loc[:, 'visits'])
print(type(df.loc[:, 'visits']))

a    1
b    3
c    2
d    3
e    2
f    3
g    1
h    1
i    2
j    1
Name: visits, dtype: int64
<class 'pandas.core.series.Series'>


In [52]:
df.sort_values(by='visits', ascending=False)

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
e    dog  5.0       2       no
i    dog  7.0       2       no
a    cat  2.5       1      yes
g  snake  4.5       1       no
h    cat  NaN       1      yes
j    dog  3.0       1       no

In [53]:
df.sort_index(by='visits', ascending=False)

TypeError: sort_index() got an unexpected keyword argument 'by'

In [54]:
df.sort_values(by='visits')

animal  age  visits priority
a    cat  2.5       1      yes
g  snake  4.5       1       no
h    cat  NaN       1      yes
j    dog  3.0       1       no
c  snake  0.5       2       no
e    dog  5.0       2       no
i    dog  7.0       2       no
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [55]:
df.sort_index(by='visits')

TypeError: sort_index() got an unexpected keyword argument 'by'

In [61]:
print((y_true-y_pred)**2)
print(((y_true-y_pred)**2).mean())
print(np.sqrt(((y_true-y_pred)**2).mean()))

[0.01   0.0004 0.0025]
0.004300000000000008
0.06557438524302006


In [62]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_true, y_pred)
print(mse)
print(np.sqrt(mse))

0.004300000000000008
0.06557438524302006


In [63]:
print(y_true)

[1. 2. 1.]


In [65]:
y_pred2 = y_true.copy()
print(y_pred2)

[1. 2. 1.]


In [67]:
mse2 = mean_squared_error(y_true, y_pred2)
print(mse2)

0.0
